version: '3'

services:

  metasploit:
    container_name: metasploit
    image: metasploitframework/metasploit-framework:latest
    environment:
      DATABASE_URL: postgres://postgres:msfpassword@db:5432/msf
    links:
      - database
    tty: true
    ports:
      - 4444:4444
    volumes:
      - $HOME/.msf4:/home/msf/.msf4

  database:
    container_name: postgres
    image: postgres:10-alpine
    environment: 
      - POSTGRES_PASSWORD=msfpassword
      - POSTGRES_DB=msf
    stdin_open: true 
    tty: true        
    volumes:
      - $PWD/database:/var/lib/postgresql/data
    ports: 
      - 5432:5432
       
